AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Parameters:
  EnvironmentName:
    Type: String
    Default: dev
Resources:
  GetReviewFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ServiceLambda/build/distributions/ServiceLambda.zip
      Handler: com.kenzie.capstone.service.lambda.GetReviewHandler
      Runtime: java11
      Description:
      MemorySize: 512
      Timeout: 240
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            Path: /review/get/{id}
            Method: get
  #  SetExampleDataFunction:
  #    Type: AWS::Serverless::Function
  #    Properties:
  #      CodeUri: ServiceLambda/build/distributions/ServiceLambda.zip
  #      Handler: com.kenzie.capstone.service.lambda.GetReviewHandler
  #      Runtime: java11
  #      Description:
  #      MemorySize: 512
  #      Timeout: 240
  #      # Function's execution role
  #      Policies:
  #        - AWSLambdaBasicExecutionRole
  #        - AWSLambda_ReadOnlyAccess
  #        - AWSXrayWriteOnlyAccess
  #        - AWSLambdaVPCAccessExecutionRole
  #        - AmazonS3FullAccess
  #        - AmazonDynamoDBFullAccess
  #      Tracing: Active
  #      Events:
  #        UpdateResource:
  #          Type: Api
  #          Properties:
  #            Path: /review/get/{id}
  #            Method: Get
  AddReviewFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ServiceLambda/build/distributions/ServiceLambda.zip
      Handler: com.kenzie.capstone.service.lambda.AddReviewHandler
      Runtime: java11
      Description:
      MemorySize: 512
      Timeout: 240
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        UpdateResource:
          Type: Api
          Properties:
            Path: /review/add
            Method: post